
# Form implementation generated from reading ui file 'RFgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 543)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 551, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_2.setObjectName("label_2")
        self.txt_Camera = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_Camera.setGeometry(QtCore.QRect(100, 20, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Camera.setFont(font)
        self.txt_Camera.setAcceptDrops(False)
        self.txt_Camera.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Camera.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Camera.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txt_Camera.setObjectName("txt_Camera")
        self.txt_Data = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_Data.setGeometry(QtCore.QRect(100, 50, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Data.setFont(font)
        self.txt_Data.setAcceptDrops(False)
        self.txt_Data.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txt_Data.setObjectName("txt_Data")
        self.btn_browsercamera = QtWidgets.QPushButton(self.groupBox)
        self.btn_browsercamera.setGeometry(QtCore.QRect(470, 20, 75, 23))
        self.btn_browsercamera.setObjectName("btn_browsercamera")
        self.btn_Browserdata = QtWidgets.QPushButton(self.groupBox)
        self.btn_Browserdata.setGeometry(QtCore.QRect(470, 50, 75, 23))
        self.btn_Browserdata.setObjectName("btn_Browserdata")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 551, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.img_Video = QtWidgets.QGraphicsView(self.groupBox_2)
        self.img_Video.setGeometry(QtCore.QRect(10, 20, 341, 251))
        self.img_Video.setObjectName("img_Video")
        self.chk_Auto = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_Auto.setGeometry(QtCore.QRect(360, 20, 131, 17))
        self.chk_Auto.setObjectName("chk_Auto")
        self.chk_Details = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_Details.setGeometry(QtCore.QRect(360, 40, 101, 17))
        self.chk_Details.setObjectName("chk_Details")
        self.btn_ScanManual = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_ScanManual.setGeometry(QtCore.QRect(460, 250, 75, 23))
        self.btn_ScanManual.setObjectName("btn_ScanManual")
        self.img_Face = QtWidgets.QGraphicsView(Dialog)
        self.img_Face.setGeometry(QtCore.QRect(20, 400, 91, 71))
        self.img_Face.setObjectName("img_Face")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 380, 91, 16))
        self.label_3.setObjectName("label_3")
        self.btn_Back = QtWidgets.QPushButton(Dialog)
        self.btn_Back.setGeometry(QtCore.QRect(30, 480, 31, 31))
        self.btn_Back.setObjectName("btn_Back")
        self.btn_Forward = QtWidgets.QPushButton(Dialog)
        self.btn_Forward.setGeometry(QtCore.QRect(70, 480, 31, 31))
        self.btn_Forward.setObjectName("btn_Forward")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 380, 441, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txt_Name = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txt_Name.setGeometry(QtCore.QRect(60, 30, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Name.setFont(font)
        self.txt_Name.setAcceptDrops(False)
        self.txt_Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txt_Name.setObjectName("txt_Name")
        self.txt_Cargo = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txt_Cargo.setGeometry(QtCore.QRect(60, 60, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_Cargo.setFont(font)
        self.txt_Cargo.setAcceptDrops(False)
        self.txt_Cargo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_Cargo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Cargo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txt_Cargo.setObjectName("txt_Cargo")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 31, 16))
        self.label_5.setObjectName("label_5")
        self.btn_Register = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Register.setGeometry(QtCore.QRect(200, 100, 75, 23))
        self.btn_Register.setObjectName("btn_Register")
        self.btn_Update = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Update.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.btn_Update.setObjectName("btn_Update")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reconhecimento Facial"))
        self.groupBox.setTitle(_translate("Dialog", "Dados"))
        self.label_2.setText(_translate("Dialog", "Fonte de dados"))
        self.btn_browsercamera.setText(_translate("Dialog", "Buscar"))
        self.btn_Browserdata.setText(_translate("Dialog", "Buscar"))
        self.label.setText(_translate("Dialog", "Fonte de imagem"))
        self.groupBox_2.setTitle(_translate("Dialog", "Vídeo"))
        self.chk_Auto.setText(_translate("Dialog", "Checagem automática"))
        self.chk_Details.setText(_translate("Dialog", "Mostrar detalhes"))
        self.btn_ScanManual.setText(_translate("Dialog", "Scan manual"))
        self.label_3.setText(_translate("Dialog", "Faces detectadas"))
        self.btn_Back.setText(_translate("Dialog", "<"))
        self.btn_Forward.setText(_translate("Dialog", ">"))
        self.groupBox_3.setTitle(_translate("Dialog", "Consulta/Registro"))
        self.label_4.setText(_translate("Dialog", "Nome:"))
        self.label_5.setText(_translate("Dialog", "Cargo:"))
        self.btn_Register.setText(_translate("Dialog", "Registrar "))
        self.btn_Update.setText(_translate("Dialog", "Alterar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

